import XCTest
@testable import SyncCastRouter

/// Settings validation, the derived geometry, and the real-time processor's
/// observable behaviour.
///
/// Everything here is offline: buffers are pushed through
/// `StereoImageProcessor` exactly the way `LocalOutput.render()` does, so a
/// regression in the DSP shows up without a CoreAudio device. The claims that
/// need a listener (does it actually widen the image?) are the user's to
/// judge; what is pinned here is that the maths does what the maths is
/// supposed to do.
final class StereoImageProcessorTests: XCTestCase {

    private let sampleRate: Double = 48_000

    // MARK: - Harness

    /// Push one block through the processor the way the render callback does.
    private func process(
        _ processor: StereoImageProcessor,
        left: inout [Float],
        right: inout [Float],
        frames: Int,
        pair: Int = 0
    ) {
        left.withUnsafeMutableBufferPointer { leftBuffer in
            right.withUnsafeMutableBufferPointer { rightBuffer in
                var pointers = [leftBuffer.baseAddress!, rightBuffer.baseAddress!]
                pointers.withUnsafeMutableBufferPointer { table in
                    processor.process(
                        pair: pair,
                        channels: table.baseAddress!,
                        channelOffset: 0,
                        channelCount: 2,
                        frames: frames
                    )
                }
            }
        }
    }

    /// Steady-state gain applied to a stereo signal generated by `sample`,
    /// measured as output RMS over input RMS on the left channel.
    ///
    /// This measures the SHIPPING code path (`process`), not the coefficient
    /// formulas, which is the point.
    private func measuredGainDb(
        _ processor: StereoImageProcessor,
        hz: Double,
        sample: (Double) -> (Double, Double),
        settleFrames: Int = 48_000,
        measureFrames: Int = 48_000
    ) -> Double {
        var inputSquares = 0.0
        var outputSquares = 0.0
        var phase = 0.0
        let increment = 2 * Double.pi * hz / sampleRate
        let block = 512
        var produced = 0
        let total = settleFrames + measureFrames

        var left = [Float](repeating: 0, count: block)
        var right = [Float](repeating: 0, count: block)
        var reference = [Double](repeating: 0, count: block)

        while produced < total {
            let frames = min(block, total - produced)
            for index in 0..<frames {
                let (l, r) = sample(phase)
                phase += increment
                reference[index] = l
                left[index] = Float(l)
                right[index] = Float(r)
            }
            process(processor, left: &left, right: &right, frames: frames)
            if produced >= settleFrames {
                for index in 0..<frames {
                    inputSquares += reference[index] * reference[index]
                    outputSquares += Double(left[index]) * Double(left[index])
                }
            }
            produced += frames
        }
        guard inputSquares > 0 else { return 0 }
        return 20 * log10(sqrt(outputSquares / inputSquares))
    }

    private func makeProcessor() -> StereoImageProcessor {
        StereoImageProcessor(pairCount: 1, channelsPerPair: 2, sampleRate: sampleRate)
    }

    // MARK: - Settings model

    func testDefaultSettingsAreNeutral() {
        let settings = StereoImageSettings.neutral
        XCTAssertTrue(settings.isNeutral)
        XCTAssertFalse(settings.hasUserSetting)
    }

    func testEnabledButUnityWidthIsStillNeutral() {
        var settings = StereoImageSettings.neutral
        settings.width.enabled = true
        settings.width.width = 1.0
        XCTAssertTrue(settings.isNeutral, "width 1 with no mid trim cannot change anything")
    }

    func testZeroStrengthIsABypassOfTheCrosstalkStage() {
        var settings = StereoImageSettings.neutral
        settings.crosstalk.enabled = true
        settings.crosstalk.strength = 0
        XCTAssertEqual(settings.crosstalk.feedbackAmplitude, 0)
        XCTAssertTrue(settings.isNeutral)
    }

    func testBypassKeepsTheSettingButStopsApplyingIt() {
        var settings = StereoImageSettings.neutral
        settings.width.enabled = true
        settings.width.width = 1.6
        settings.bypassed = true
        XCTAssertTrue(settings.isNeutral, "a bypassed module must take the fast path")
        XCTAssertTrue(settings.hasUserSetting, "…without losing what the user dialled in")
    }

    func testDerivedDelayMatchesTheGeometry() {
        let crosstalk = StereoCrosstalkSettings(enabled: true)
        // span·ear/distance / c = 0.17·0.15/0.65 / 343 ≈ 114 µs.
        XCTAssertEqual(crosstalk.delaySeconds, 114.4e-6, accuracy: 1e-6)
        XCTAssertEqual(crosstalk.delaySamples(sampleRate: 48_000), 5.49, accuracy: 0.02)
        // Halving the distance doubles the path difference and so the delay.
        var nearer = crosstalk
        nearer.distanceMeters = 0.325
        XCTAssertEqual(nearer.delaySeconds, 2 * crosstalk.delaySeconds, accuracy: 1e-9)
    }

    func testDelayIsHeldAtOneWholeSampleForExtremeGeometry() {
        // The recursion reads its own past output; a delay below one sample
        // would need the sample being computed.
        var crosstalk = StereoCrosstalkSettings(enabled: true)
        crosstalk.spanMeters = 0.05
        crosstalk.distanceMeters = 3.0
        XCTAssertLessThan(crosstalk.delaySeconds * 48_000, 1)
        XCTAssertEqual(crosstalk.delaySamples(sampleRate: 48_000), 1)
    }

    func testFeedbackStaysStrictlyInsideTheUnitCircle() {
        for db in stride(from: -6.0, through: -1.0, by: 0.25) {
            var crosstalk = StereoCrosstalkSettings(enabled: true)
            crosstalk.attenuationDb = db
            crosstalk.strength = 1
            XCTAssertLessThan(
                crosstalk.feedbackAmplitude, 1,
                "|a| < 1 is the stability condition, at every legal attenuation"
            )
        }
    }

    func testSanitizationClampsGarbageAndKeepsTheBandOrdered() {
        var settings = StereoImageSettings()
        settings.width.enabled = true
        settings.width.width = 99
        settings.width.cornerHz = .nan
        settings.width.midTrimDb = -40
        settings.crosstalk.enabled = true
        settings.crosstalk.attenuationDb = 12
        settings.crosstalk.strength = .infinity
        settings.crosstalk.spanMeters = -3
        settings.crosstalk.lowHz = 4_000
        settings.crosstalk.highHz = 2_000
        let clean = settings.sanitized()
        XCTAssertEqual(clean.width.width, 2)
        XCTAssertEqual(clean.width.cornerHz, StereoImageLimits.defaultWidthCornerHz)
        XCTAssertEqual(clean.width.midTrimDb, -1)
        XCTAssertEqual(clean.crosstalk.attenuationDb, -1)
        XCTAssertEqual(clean.crosstalk.strength, StereoImageLimits.defaultStrength)
        XCTAssertEqual(clean.crosstalk.spanMeters, 0.05)
        XCTAssertGreaterThan(
            clean.crosstalk.highHz, clean.crosstalk.lowHz,
            "an inverted band would make the split filters fight each other"
        )
    }

    func testCodableRoundTripSurvivesAMissingField() throws {
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(
            enabled: true, width: 1.55, cornerHz: 1_800, midTrimDb: -0.5
        )
        settings.crosstalk = StereoCrosstalkSettings(
            enabled: true, attenuationDb: -3.5, strength: 0.8,
            spanMeters: 0.2, distanceMeters: 0.8, lowHz: 1_200, highHz: 6_000
        )
        let data = try JSONEncoder().encode(settings)
        XCTAssertEqual(try JSONDecoder().decode(StereoImageSettings.self, from: data), settings)
        // A record written before a field existed decodes to that field's
        // default rather than throwing.
        let partial = Data(#"{"width":{"enabled":true,"width":1.2}}"#.utf8)
        let decoded = try JSONDecoder().decode(StereoImageSettings.self, from: partial)
        XCTAssertEqual(decoded.width.width, 1.2)
        XCTAssertEqual(decoded.width.cornerHz, StereoImageLimits.defaultWidthCornerHz)
        XCTAssertFalse(decoded.crosstalk.enabled)
    }

    // MARK: - Bypass fast path

    func testNeutralSettingsLeaveTheBufferBitIdentical() {
        let processor = makeProcessor()
        // Both stages ON but at their no-op values — the case a naive "is the
        // toggle on?" check would get wrong.
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(enabled: true, width: 1.0, midTrimDb: 0)
        settings.crosstalk = StereoCrosstalkSettings(enabled: true, strength: 0)
        processor.setSettings(settings, pair: 0)

        let frames = 512
        var left = [Float](repeating: 0, count: frames)
        var right = [Float](repeating: 0, count: frames)
        for index in 0..<frames {
            left[index] = Float(sin(Double(index) * 0.031)) * 0.7
            right[index] = Float(cos(Double(index) * 0.017)) * 0.5
        }
        let expectedLeft = left
        let expectedRight = right
        for _ in 0..<8 {
            var blockLeft = expectedLeft
            var blockRight = expectedRight
            process(processor, left: &blockLeft, right: &blockRight, frames: frames)
            XCTAssertEqual(blockLeft, expectedLeft)
            XCTAssertEqual(blockRight, expectedRight)
        }
        XCTAssertEqual(processor.clipCount, 0)
        XCTAssertFalse(processor.isEngaged)
    }

    func testBypassIsBitIdenticalEvenWithBothStagesDialledIn() {
        let processor = makeProcessor()
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(enabled: true, width: 1.8, midTrimDb: -0.8)
        settings.crosstalk = StereoCrosstalkSettings(enabled: true, strength: 1)
        settings.bypassed = true
        processor.setSettings(settings, pair: 0)

        let frames = 256
        var left = [Float](repeating: 0, count: frames)
        var right = [Float](repeating: 0, count: frames)
        for index in 0..<frames {
            left[index] = Float(sin(Double(index) * 0.05)) * 0.6
            right[index] = Float(sin(Double(index) * 0.05 + 1.1)) * 0.6
        }
        let expectedLeft = left
        let expectedRight = right
        process(processor, left: &left, right: &right, frames: frames)
        XCTAssertEqual(left, expectedLeft)
        XCTAssertEqual(right, expectedRight)
    }

    // MARK: - Width stage

    func testPureMidSignalIsUnchangedAtAnyWidth() {
        // L == R means S == 0, and the stage only ever scales S. This is the
        // mono-compatibility property, asserted at the sample level rather
        // than argued for in a comment.
        for width in [0.0, 0.5, 1.4, 2.0] {
            let processor = makeProcessor()
            var settings = StereoImageSettings()
            settings.width = StereoWidthSettings(
                enabled: true, width: width, cornerHz: 1_500, midTrimDb: 0
            )
            processor.setSettings(settings, pair: 0)

            let frames = 1_024
            var left = [Float](repeating: 0, count: frames)
            for index in 0..<frames {
                left[index] = Float(sin(Double(index) * 0.09) * 0.4)
            }
            var right = left
            let expected = left
            process(processor, left: &left, right: &right, frames: frames)
            XCTAssertEqual(left, expected, "width \(width) moved a mono signal")
            XCTAssertEqual(right, expected, "width \(width) moved a mono signal")
        }
    }

    func testSideSignalScalesByWidthAboveTheCorner() {
        let width = 1.4
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(enabled: true, width: width, cornerHz: 1_500)

        // Well above the corner the side high-pass is asymptotically unity, so
        // the achieved gain is the width itself.
        let far = makeProcessor()
        far.setSettings(settings, pair: 0)
        let farGain = measuredGainDb(far, hz: 9_600) { (sin($0) * 0.3, -sin($0) * 0.3) }
        XCTAssertEqual(farGain, 20 * log10(width), accuracy: 0.2)

        // One octave above a second-order corner the high-pass is at 0.97 with
        // 43° of phase, so `S + (width−1)·HP(S)` lands a little short of the
        // full width. That shortfall is the documented cost of leaving the
        // side signal untouched below the corner rather than crossing it over.
        let near = makeProcessor()
        near.setSettings(settings, pair: 0)
        let nearGain = measuredGainDb(near, hz: 3_000) { (sin($0) * 0.3, -sin($0) * 0.3) }
        XCTAssertEqual(nearGain, 20 * log10(width), accuracy: 0.7)
        XCTAssertGreaterThan(nearGain, 1.0, "3 kHz must already be well into the widened band")
    }

    func testSideSignalIsUntouchedBelowTheCorner() {
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(enabled: true, width: 1.4, cornerHz: 1_500)
        let processor = makeProcessor()
        processor.setSettings(settings, pair: 0)
        let gain = measuredGainDb(processor, hz: 300) { (sin($0) * 0.3, -sin($0) * 0.3) }
        XCTAssertEqual(gain, 0, accuracy: 0.3)
    }

    func testMidTrimAttenuatesOnlyTheMidSignal() {
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(
            enabled: true, width: 1.0, cornerHz: 1_500, midTrimDb: -1
        )
        let processor = makeProcessor()
        processor.setSettings(settings, pair: 0)
        let midGain = measuredGainDb(processor, hz: 1_000) { (sin($0) * 0.3, sin($0) * 0.3) }
        XCTAssertEqual(midGain, -1, accuracy: 0.05)

        let sideProcessor = makeProcessor()
        sideProcessor.setSettings(settings, pair: 0)
        let sideGain = measuredGainDb(sideProcessor, hz: 3_000) {
            (sin($0) * 0.3, -sin($0) * 0.3)
        }
        XCTAssertEqual(sideGain, 0, accuracy: 0.05)
    }

    // MARK: - Crosstalk stage

    /// Settings with both halves of the band split switched off, so the
    /// recursion can be observed on its own.
    ///
    /// This is a real configuration, not a test hook: the low edge at its
    /// minimum means "no low edge", and a high edge at or above 45% of the
    /// sample rate cannot be realised as a second-order section, so both are
    /// skipped rather than run.
    private func fullBandCrosstalk(attenuationDb: Double = -2.5) -> StereoImageSettings {
        var settings = StereoImageSettings()
        settings.crosstalk = StereoCrosstalkSettings(
            enabled: true,
            attenuationDb: attenuationDb,
            strength: 1,
            lowHz: StereoImageLimits.crosstalkLowRangeHz.lowerBound,
            highHz: StereoImageLimits.crosstalkHighRangeHz.upperBound
        )
        return settings
    }

    func testImpulseInLeftProducesTheRecursiveTail() {
        let settings = fullBandCrosstalk()
        let a = settings.crosstalk.feedbackAmplitude
        let delay = settings.crosstalk.delaySamples(sampleRate: sampleRate)
        XCTAssertEqual(a, pow(10, -2.5 / 20), accuracy: 1e-9)

        let processor = makeProcessor()
        processor.setSettings(settings, pair: 0)

        // The first publish starts a 20 ms crossfade out of the neutral bank,
        // exactly as a live edit would. Let it finish on silence, so what the
        // impulse then measures is the settled recursion and not the fade.
        let frames = 64
        var left = [Float](repeating: 0, count: frames)
        var right = [Float](repeating: 0, count: frames)
        for _ in 0..<Int((sampleRate * 0.04).rounded()) / frames {
            for index in 0..<frames {
                left[index] = 0
                right[index] = 0
            }
            process(processor, left: &left, right: &right, frames: frames)
        }
        for index in 0..<frames {
            left[index] = 0
            right[index] = 0
        }
        left[0] = 1
        process(processor, left: &left, right: &right, frames: frames)

        // Solving the recursion for L = δ, R = 0:
        //   R' has taps at τ, 3τ, 5τ … with −a, −a³, −a⁵
        //   L' has taps at 0, 2τ, 4τ … with  1,  a²,  a⁴
        // τ is 5.49 samples here, so each "tap" is spread over the two (for
        // the first reflection) or three (for the second) samples the linear
        // interpolator touches. The interpolator has unity DC gain, so the
        // AREA of each tap is exact and that is what is asserted.
        let firstWindow = 1...Int((2 * delay).rounded(.down))
        let firstEcho = firstWindow.reduce(0.0) { $0 + Double(right[$1]) }
        XCTAssertEqual(firstEcho, -a, accuracy: 1e-5, "first echo: −a at τ, in the OTHER channel")

        let secondWindow = Int(delay.rounded(.up))...Int((3 * delay).rounded(.down))
        let secondEcho = secondWindow.reduce(0.0) { $0 + Double(left[$1]) }
        XCTAssertEqual(secondEcho, a * a, accuracy: 1e-5, "second echo: +a² at 2τ, back in L")

        XCTAssertEqual(Double(left[0]), 1, accuracy: 1e-6, "the direct sound is untouched")
        // Nothing arrives before the first echo can physically have travelled.
        for index in 1..<Int(delay.rounded(.down)) {
            XCTAssertEqual(Double(right[index]), 0, accuracy: 1e-7)
        }
    }

    func testRecursionIsStableAtTheStrongestLegalSetting() {
        // a = 10^(−1/20) = 0.891 at full strength: the worst case the ranges
        // allow, and the one where an unstable structure would run away.
        let settings = fullBandCrosstalk(attenuationDb: -1)
        let processor = makeProcessor()
        processor.setSettings(settings, pair: 0)

        var generator = SystemRandomNumberGenerator()
        let block = 1_024
        var left = [Float](repeating: 0, count: block)
        var right = [Float](repeating: 0, count: block)
        let noiseBlocks = Int(10 * sampleRate) / block   // 10 seconds

        for _ in 0..<noiseBlocks {
            for index in 0..<block {
                left[index] = Float(Double.random(in: -0.5...0.5, using: &generator))
                right[index] = Float(Double.random(in: -0.5...0.5, using: &generator))
            }
            process(processor, left: &left, right: &right, frames: block)
            for index in 0..<block {
                XCTAssertTrue(left[index].isFinite && right[index].isFinite)
                XCTAssertLessThanOrEqual(abs(left[index]), 1)
                XCTAssertLessThanOrEqual(abs(right[index]), 1)
            }
        }

        // Then a second of silence: a stable structure decays to nothing. A
        // marginally stable or growing one would still be ringing.
        var tailPeak: Float = 0
        for blockIndex in 0..<Int(sampleRate) / block {
            for index in 0..<block {
                left[index] = 0
                right[index] = 0
            }
            process(processor, left: &left, right: &right, frames: block)
            if blockIndex >= 4 {
                for index in 0..<block {
                    tailPeak = max(tailPeak, max(abs(left[index]), abs(right[index])))
                }
            }
        }
        XCTAssertLessThan(tailPeak, 1e-5, "the recursion must decay once the input stops")
    }

    func testBandSplitPassesOutOfBandTonesUnchanged() {
        // Low side: the default band starts at 1500 Hz, so 60 Hz is four and a
        // half octaves down a 12 dB/octave skirt.
        var lowSettings = StereoImageSettings()
        lowSettings.crosstalk = StereoCrosstalkSettings(enabled: true, strength: 1)
        let lowProcessor = makeProcessor()
        lowProcessor.setSettings(lowSettings, pair: 0)
        let lowGain = measuredGainDb(lowProcessor, hz: 60) { (sin($0) * 0.3, sin($0) * 0.3) }
        XCTAssertEqual(lowGain, 0, accuracy: 0.1)

        // High side: with the band's upper edge pulled down to 2 kHz, a 20 kHz
        // tone is three and a third octaves above it.
        var highSettings = StereoImageSettings()
        highSettings.crosstalk = StereoCrosstalkSettings(
            enabled: true, strength: 1,
            lowHz: StereoImageLimits.crosstalkLowRangeHz.lowerBound, highHz: 2_000
        )
        let highProcessor = makeProcessor()
        highProcessor.setSettings(highSettings, pair: 0)
        let highGain = measuredGainDb(highProcessor, hz: 20_000) {
            (sin($0) * 0.3, sin($0) * 0.3)
        }
        XCTAssertEqual(highGain, 0, accuracy: 0.1)
    }

    func testCorrelatedContentSeesTheDocumentedColourationPeak() {
        // The recursion's own peak on centred content, `1/(1−a)` at 1/(2τ).
        // Asserted because it is the number the UI warns with and the reason
        // the limiter exists — if the structure ever stopped doing this, the
        // warning would be lying.
        let settings = fullBandCrosstalk()
        let processor = makeProcessor()
        processor.setSettings(settings, pair: 0)
        let peakHz = settings.crosstalk.peakColourationHz
        XCTAssertEqual(peakHz, 4_371, accuracy: 40)
        let gain = measuredGainDb(processor, hz: peakHz) { (sin($0) * 0.1, sin($0) * 0.1) }

        // What is actually measured is a little BELOW the closed-form peak,
        // and by a knowable amount: the linear interpolator in the feedback
        // path has magnitude `sqrt(1 − 2d(1−d)(1−cos ω))` rather than 1, so
        // the effective `a` at the peak frequency is reduced. This is the HF
        // error the fractional-delay choice was made with open eyes, pinned
        // here so a future switch to an allpass interpolator shows up.
        let delay = settings.crosstalk.delaySamples(sampleRate: sampleRate)
        let fraction = delay - delay.rounded(.down)
        let omega = 2 * Double.pi * peakHz / sampleRate
        let interpolator = sqrt(1 - 2 * fraction * (1 - fraction) * (1 - cos(omega)))
        let effective = settings.crosstalk.feedbackAmplitude * interpolator
        XCTAssertEqual(gain, -20 * log10(1 - effective), accuracy: 0.4)
        XCTAssertLessThan(
            gain, settings.crosstalk.peakColourationDb + 0.1,
            "the UI's warning figure must never understate what is heard"
        )
    }

    // MARK: - Limiter

    func testClipCounterCountsClampedSamplesAndOutputStaysInRange() {
        let processor = makeProcessor()
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(enabled: true, width: 2.0, cornerHz: 200)
        processor.setSettings(settings, pair: 0)

        let frames = 1_024
        var left = [Float](repeating: 0, count: frames)
        var right = [Float](repeating: 0, count: frames)
        for index in 0..<frames {
            let value = Float(sin(Double(index) * 0.4) * 0.9)
            left[index] = value
            right[index] = -value
        }
        process(processor, left: &left, right: &right, frames: frames)

        XCTAssertGreaterThan(processor.clipCount, 0, "doubling a 0.9 side signal must clip")
        for index in 0..<frames {
            XCTAssertLessThanOrEqual(abs(left[index]), 1)
            XCTAssertLessThanOrEqual(abs(right[index]), 1)
        }
        processor.resetClipCount()
        XCTAssertEqual(processor.clipCount, 0)
    }

    // MARK: - Publish / crossfade

    func testRepublishingTheSameSettingsIsANoOp() {
        let processor = makeProcessor()
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(enabled: true, width: 1.5)
        XCTAssertTrue(processor.setSettings(settings, pair: 0))
        XCTAssertFalse(
            processor.setSettings(settings, pair: 0),
            "the Router re-pushes its whole map on every replan; that must be free"
        )
        XCTAssertTrue(processor.isEngaged)
    }

    func testParameterChangeIsCrossfadedRatherThanStepped() {
        // A 100 Hz side-only tone: its own sample-to-sample step is tiny, so
        // an un-faded coefficient swap would stand out as a large first
        // difference. Compare a run that changes settings mid-stream against
        // one that does not.
        func run(changeAt changeBlock: Int?) -> Double {
            let processor = makeProcessor()
            var settings = StereoImageSettings()
            settings.width = StereoWidthSettings(enabled: true, width: 1.0, cornerHz: 200)
            processor.setSettings(settings, pair: 0)

            let block = 256
            var phase = 0.0
            let increment = 2 * Double.pi * 100 / sampleRate
            var left = [Float](repeating: 0, count: block)
            var right = [Float](repeating: 0, count: block)
            var previous: Float = 0
            var maxStep = 0.0
            for blockIndex in 0..<64 {
                if blockIndex == changeBlock {
                    var changed = settings
                    changed.width.width = 2.0
                    processor.setSettings(changed, pair: 0)
                }
                for index in 0..<block {
                    let value = Float(sin(phase) * 0.4)
                    phase += increment
                    left[index] = value
                    right[index] = -value
                }
                process(processor, left: &left, right: &right, frames: block)
                for index in 0..<block {
                    maxStep = max(maxStep, Double(abs(left[index] - previous)))
                    previous = left[index]
                }
            }
            return maxStep
        }
        let steady = run(changeAt: nil)
        let switched = run(changeAt: 20)
        XCTAssertLessThan(
            switched, steady * 2,
            "a 20 ms crossfade must keep the change below a visible step"
        )
    }

    func testResetAllReturnsEveryPairToNeutral() {
        let processor = StereoImageProcessor(
            pairCount: 3, channelsPerPair: 2, sampleRate: sampleRate
        )
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(enabled: true, width: 1.7)
        for pair in 0..<3 { processor.setSettings(settings, pair: pair) }
        XCTAssertTrue(processor.isEngaged)
        processor.resetAll()
        XCTAssertFalse(processor.isEngaged)
    }

    func testOutOfRangePairAndOversizedBlockAreRefusedNotFatal() {
        let processor = makeProcessor()
        var settings = StereoImageSettings()
        settings.width = StereoWidthSettings(enabled: true, width: 1.7)
        XCTAssertFalse(processor.setSettings(settings, pair: 4))
        processor.setSettings(settings, pair: 0)

        // A block longer than the scratch buffers is left alone rather than
        // served from a short buffer.
        let frames = StereoImageProcessor.maxFramesPerBlock + 1
        var left = [Float](repeating: 0.5, count: frames)
        var right = [Float](repeating: -0.5, count: frames)
        let expected = left
        process(processor, left: &left, right: &right, frames: frames)
        XCTAssertEqual(left, expected)
    }
}
